version: '3'
services:
  database:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db

  astracore-node:
    build: .
    image: astracore-node
    links:
      - database
    ports:
      - 8100:8100
      - 3000:3000
    environment:
      - DB_HOST=database
    env_file: .env
#insight:
#image: insight
#links:
#- astracore-node
#environment:
#- API_URL=astracore-node
