FROM node:10

# Install Chrome

RUN echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/chrome.list

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

RUN set -x \
    && apt-get update \
    && apt-get install -y \
        google-chrome-stable

ENV CHROME_BIN /usr/bin/google-chrome

# Log versions

RUN set -x \
    && node -v \
    && npm -v \
    && google-chrome --version


RUN npm i -g npm@6.4.1

WORKDIR /astracore

# Add source
COPY lerna.json ./
COPY package*.json ./

COPY  ./packages/astracore-client/package.json ./packages/astracore-client/package.json
COPY  ./packages/astracore-client/package-lock.json ./packages/astracore-client/package-lock.json

COPY  ./packages/astracore-build/package.json ./packages/astracore-build/package.json
COPY  ./packages/astracore-build/package-lock.json ./packages/astracore-build/package-lock.json

COPY  ./packages/astracore-lib-cash/package.json ./packages/astracore-lib-cash/package.json
COPY  ./packages/astracore-lib-cash/package-lock.json ./packages/astracore-lib-cash/package-lock.json

COPY  ./packages/astracore-lib/package.json ./packages/astracore-lib/package.json
COPY  ./packages/astracore-lib/package-lock.json ./packages/astracore-lib/package-lock.json

COPY  ./packages/astracore-mnemonic/package.json ./packages/astracore-mnemonic/package.json
COPY  ./packages/astracore-mnemonic/package-lock.json ./packages/astracore-mnemonic/package-lock.json

COPY  ./packages/astracore-node/package.json ./packages/astracore-node/package.json
COPY  ./packages/astracore-node/package-lock.json ./packages/astracore-node/package-lock.json

COPY  ./packages/astracore-p2p-cash/package.json ./packages/astracore-p2p-cash/package.json
COPY  ./packages/astracore-p2p-cash/package-lock.json ./packages/astracore-p2p-cash/package-lock.json

COPY  ./packages/astracore-p2p/package.json ./packages/astracore-p2p/package.json
COPY  ./packages/astracore-p2p/package-lock.json ./packages/astracore-p2p/package-lock.json

COPY  ./packages/astracore-wallet-client/package.json ./packages/astracore-wallet-client/package.json
COPY  ./packages/astracore-wallet-client/package-lock.json ./packages/astracore-wallet-client/package-lock.json

COPY  ./packages/astracore-wallet-service/package.json ./packages/astracore-wallet-service/package.json
COPY  ./packages/astracore-wallet-service/package-lock.json ./packages/astracore-wallet-service/package-lock.json

COPY  ./packages/astracore-wallet/package.json ./packages/astracore-wallet/package.json
COPY  ./packages/astracore-wallet/package-lock.json ./packages/astracore-wallet/package-lock.json

COPY  ./packages/insight/package.json ./packages/insight/package.json
COPY  ./packages/insight/package-lock.json ./packages/insight/package-lock.json

COPY  ./packages/crypto-wallet-core/package.json ./packages/crypto-wallet-core/package.json
COPY  ./packages/crypto-wallet-core/package-lock.json ./packages/crypto-wallet-core/package-lock.json

COPY  ./packages/astracore-lib-ltc/package.json ./packages/astracore-lib-ltc/package.json
COPY  ./packages/astracore-lib-ltc/package-lock.json ./packages/astracore-lib-ltc/package-lock.json


RUN npm install
RUN npm run bootstrap
ADD . .
RUN npm run compile
